FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    python3-dev \
    python3-venv \
    python3-pip \
    git \
    pkg-config \
    linux-tools-generic \
    ninja-build \
    wget \
    cmake \
    ccache \
    doxygen \
    graphviz \
    curl \
    jq \
    gh \
    lcov

RUN apt-get clean
