#!/bin/bash
#
# probe_agent.sh - Create specialized agents for different sections of tt-llk
#
# This script spawns agents IN PARALLEL scoped to specific hardware targets or
# test directories, ensuring each agent only operates within its designated section.
# Each agent outputs a markdown report to .cursor/Reports/<section>.md
#
# Usage:
#   ./probe_agent.sh "Your task description here"
#
# Example:
#   ./probe_agent.sh "Analyze the math operations and document their usage"
#
# Output:
#   Reports are saved to: .cursor/Reports/<section_name>.md
#

set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPORTS_DIR="$WORKSPACE_ROOT/.cursor/Reports"

# List of sections to probe (hardware targets + tests)
SECTIONS=(
    "tt_llk_blackhole"
    "tt_llk_wormhole_b0"
    "tt_llk_quasar"
    "tests"
)

# =============================================================================
# Input Validation
# =============================================================================

# Get the description from the first argument
DESCRIPTION="${1:-}"

if [[ -z "$DESCRIPTION" ]]; then
    echo "Error: No description provided"
    echo ""
    echo "Usage: $0 \"<task description>\""
    echo ""
    echo "Example:"
    echo "  $0 \"Analyze the llk_lib headers and list all public functions\""
    exit 1
fi

# =============================================================================
# Setup
# =============================================================================

# Create reports directory if it doesn't exist
mkdir -p "$REPORTS_DIR"

# Timestamp for the report
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

echo "========================================"
echo "Probe Agent - Starting PARALLEL multi-section analysis"
echo "========================================"
echo ""
echo "Task: $DESCRIPTION"
echo "Sections: ${SECTIONS[*]}"
echo "Reports: $REPORTS_DIR"
echo ""

# =============================================================================
# Agent Function (runs in background)
# =============================================================================

run_agent() {
    local SECTION="$1"
    local DESCRIPTION="$2"
    local REPORT_FILE="$REPORTS_DIR/${SECTION}.md"
    local TEMP_OUTPUT=$(mktemp)

    echo "[→] Starting agent for: $SECTION"

    # Build context restriction and report format instructions
    PRE_CONTEXT="<critical-restriction>
You are an agent scoped to the '$SECTION' directory only.
- You MUST only work within the '$SECTION' directory
- Do NOT modify or read files outside of '$SECTION'
- Focus your analysis and changes exclusively on this section
</critical-restriction>

<output-format>
Your response will be saved as a markdown report. Structure your output as follows:
- Use proper markdown formatting (headers, lists, tables, code blocks)
- Be clear and concise
- Include relevant file paths and code snippets where appropriate
- End with a summary section
</output-format>"

    # Combine pre-context with user description
    FINAL_PROMPT="${PRE_CONTEXT}

## Task
${DESCRIPTION}"

    # Run the agent and capture output
    if agent -p --force "$FINAL_PROMPT" > "$TEMP_OUTPUT" 2>&1; then
        # Create the markdown report
        {
            echo "# Report: ${SECTION}"
            echo ""
            echo "**Generated:** ${TIMESTAMP}"
            echo ""
            echo "**Task:** ${DESCRIPTION}"
            echo ""
            echo "---"
            echo ""
            cat "$TEMP_OUTPUT"
            echo ""
            echo "---"
            echo ""
            echo "*Report generated by probe_agent.sh*"
        } > "$REPORT_FILE"

        echo "[✓] Agent completed: $SECTION → $REPORT_FILE"
        rm -f "$TEMP_OUTPUT"
        return 0
    else
        # Create error report
        {
            echo "# Report: ${SECTION}"
            echo ""
            echo "**Generated:** ${TIMESTAMP}"
            echo ""
            echo "**Task:** ${DESCRIPTION}"
            echo ""
            echo "---"
            echo ""
            echo "## ⚠️ Agent Error"
            echo ""
            echo "The agent encountered an error while processing this section."
            echo ""
            echo "### Error Output"
            echo ""
            echo '```'
            cat "$TEMP_OUTPUT"
            echo '```'
            echo ""
            echo "---"
            echo ""
            echo "*Report generated by probe_agent.sh*"
        } > "$REPORT_FILE"

        echo "[✗] Agent failed: $SECTION → $REPORT_FILE (see report for details)"
        rm -f "$TEMP_OUTPUT"
        return 1
    fi
}

# =============================================================================
# Main Logic - Run Agents in Parallel
# =============================================================================

# Array to store background process PIDs
declare -a PIDS=()

# Launch all agents in parallel
for SECTION in "${SECTIONS[@]}"; do
    run_agent "$SECTION" "$DESCRIPTION" &
    PIDS+=($!)
done

echo ""
echo "Launched ${#PIDS[@]} agents in parallel. Waiting for completion..."
echo ""

# Wait for all background processes and track results
declare -A RESULTS
FAILED=0

for i in "${!SECTIONS[@]}"; do
    SECTION="${SECTIONS[$i]}"
    PID="${PIDS[$i]}"

    if wait "$PID"; then
        RESULTS["$SECTION"]="SUCCESS"
    else
        RESULTS["$SECTION"]="FAILED"
        ((FAILED++)) || true
    fi
done

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "========================================"
echo "Probe Agent - Summary"
echo "========================================"
echo ""
echo "Reports generated in: $REPORTS_DIR"
echo ""

for SECTION in "${SECTIONS[@]}"; do
    STATUS="${RESULTS[$SECTION]}"
    REPORT_FILE="$REPORTS_DIR/${SECTION}.md"
    if [[ "$STATUS" == "SUCCESS" ]]; then
        echo "  [✓] $SECTION → ${SECTION}.md"
    else
        echo "  [✗] $SECTION → ${SECTION}.md (error)"
    fi
done

echo ""
echo "========================================"

# Exit with error if any agent failed
if [[ $FAILED -gt 0 ]]; then
    echo "Warning: $FAILED agent(s) failed. Check reports for details."
    exit 1
fi

echo "All agents completed successfully!"
