name: 🧩 tt-metal integration

on:
  pull_request:
    types: [labeled]

jobs:
  test-tt-metal:
    name: "🧪 Running tests (Wormhole)"
    needs: setup-and-test-wormhole
    uses: ./.github/workflows/tt-metal-integration-tests.yml
    secrets: inherit
    with:
      branch_name: ${{ github.head_ref }}
      runs_on: tt-beta-ubuntu-2204-n150-large-stable
