# Run pre-commit hooks
name: Run pre-commit hooks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so 'origin/main' is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run pre-commit and fix issues
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--from-ref origin/main --to-ref HEAD"
