name: Trigger tt-metal CI

on:
  push:
    branches: [main-like] # need to change to main once verified

permissions:
  contents: read
  actions: write

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event to tt-metal
        run: |
          curl -X POST https://api.github.com/repos/tenstorrent/tt-metal/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "trigger-ci", "client_payload": {"source": "tt-llk"}}'
