on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name to check out in tt-metal"
        required: true
        type: string
      runs_on:
        description: "Runner to use for the job"
        required: true
        type: string

jobs:
  test-tt-metal:
    name: 🔧 LLK unit tests
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 40
    container:
      image: ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-22.04-ci-build-amd64:latest
      options: --user root --device /dev/tenstorrent --rm
      volumes:
        - /dev/hugepages:/dev/hugepages
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /lib/modules:/lib/modules

    steps:
      - name: Checkout tt-metal repository with submodules
        uses: actions/checkout@v4
        with:
          repository: tenstorrent/tt-metal
          token: ${{ secrets.GITHUB_TOKEN }}
          path: tt-metal
          submodules: recursive
          fetch-depth: 500 # Need enough history for `git describe`
          fetch-tags: true # Need tags for `git describe`

      - name: Override LLK submodule branch
        run: |
          cd tt-metal/tt_metal/third_party/tt_llk

          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "PR is from a fork: ${{ github.event.pull_request.head.repo.full_name }}"

            # Extract the contributor's username from the fork's full name
            contributor_name=$(echo "${{ github.event.pull_request.head.repo.full_name }}" | cut -d'/' -f1)
            echo "Contributor's username: $contributor_name"

            remote_url="https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git"
            echo "Adding contributor's fork as remote..."
            git remote add $contributor_name $remote_url || echo "Remote already exists"

            echo "Fetching branch '${{ github.head_ref }}' from fork..."
            git fetch $contributor_name ${{ github.head_ref }}

            echo "Checking out the fork branch"
            git checkout FETCH_HEAD
          else
            echo "PR is internal (same repo). Using origin to checkout submodule branch"

            echo "Fetching all branches from origin..."
            git fetch origin +refs/heads/*:refs/remotes/origin/*

            echo "Checking out branch '${{ github.head_ref }}' from origin"
            git checkout remotes/origin/${{ github.head_ref }}
          fi

          cd ../../../../

      - name: Run tests in Docker container
        run: |
          cd tt-metal
          export TT_METAL_HOME=$(pwd)
          export PYTHONPATH=$(pwd)
          ./build_metal.sh --build-metal-tests
          TT_METAL_SLOW_DISPATCH_MODE=1 ./build_Release/test/tt_metal/unit_tests_llk

  ttnn-tests:
    runs-on: tt-beta-ubuntu-2204-large
    secrets: inherit
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Trigger TTNN tests in another repository
        run: |
          gh workflow run ttnn-post-commit-wrapper.yaml \
            --repo tenstorrent/tt-metal \
            --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for workflow to start
        run: sleep 10

      - name: Fetch workflow run details
        id: fetch-run
        run: |
          run_details=$(gh run list --repo tenstorrent/tt-metal --workflow ttnn-post-commit-wrapper.yaml \
          --branch main --limit 1 --json databaseId,url --jq '.[0]')
          echo "Run details: $run_details"

          # Extract the Run ID and URL
          echo "run_id=$(echo $run_details | jq -r '.databaseId')" >> $GITHUB_ENV
          echo "run_url=$(echo $run_details | jq -r '.url')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post comment on PR with Run ID and link
        if: github.event.pull_request != null
        uses: actions/github-script@v7
        with:
          script: |
            const runId = process.env.run_id;
            const runUrl = process.env.run_url;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `The TTNN workflow has been triggered in the other repository. \
              Run ID: **${runId}**. [View Run](${runUrl})`
            });
